import { internalMutation } from "./_generated/server";

export const seed = internalMutation({
  args: {},
  handler: async (ctx) => {
    const now = Date.now();

    // ── Users ──
    // Damon — primary admin (uses Google sign-in via damonbodine@gmail.com)
    const damonUser = await ctx.db.insert("users", {
      clerkId: "user_3BKO1mVZeYBph4mcp8lzDMKS7Tq",
      name: "Damon Bodine",
      email: "damonbodine@gmail.com",
      role: "Admin",
      bio: "Platform owner",
      isActive: true,
      createdAt: now,
      updatedAt: now,
    });

    const adminUser = await ctx.db.insert("users", {
      clerkId: "user_3BRH9XIJ7LuaV1Hte9MqzawDxLQ",
      name: "Sarah Admin",
      email: "admin@pawmatch.dev",
      phone: "512-555-0001",
      role: "Admin",
      bio: "Platform administrator",
      isActive: true,
      createdAt: now,
      updatedAt: now,
    });

    const staffUser1 = await ctx.db.insert("users", {
      clerkId: "user_3BRH9ahcbN9bP8zvJvJBJm0mgoT",
      name: "Mike Handler",
      email: "staff@pawmatch.dev",
      phone: "512-555-0002",
      role: "ShelterStaff",
      bio: "Animal care specialist with 10 years experience",
      isActive: true,
      createdAt: now,
      updatedAt: now,
    });

    const staffUser2 = await ctx.db.insert("users", {
      clerkId: "clerk_staff_002",
      name: "Lisa Caretaker",
      email: "lisa@petsafe.org",
      phone: "512-555-0003",
      role: "ShelterStaff",
      bio: "Veterinary technician and volunteer coordinator",
      isActive: true,
      createdAt: now,
      updatedAt: now,
    });

    const adopter1 = await ctx.db.insert("users", {
      clerkId: "user_3BRH9bAxRNIcYxp71MiTrUzhDdw",
      name: "Jane Adopter",
      email: "adopter@pawmatch.dev",
      phone: "512-555-0004",
      role: "Adopter",
      bio: "Dog lover looking for a companion",
      isActive: true,
      createdAt: now,
      updatedAt: now,
    });

    const adopter2 = await ctx.db.insert("users", {
      clerkId: "clerk_adopter_002",
      name: "James Wilson",
      email: "james@example.com",
      phone: "512-555-0005",
      role: "Adopter",
      bio: "Family of four looking for a family pet",
      isActive: true,
      createdAt: now,
      updatedAt: now,
    });

    // ── Shelters ──
    const shelter1 = await ctx.db.insert("shelters", {
      name: "Happy Tails Rescue",
      address: "123 Bark Street",
      city: "Austin",
      state: "TX",
      zipCode: "78701",
      phone: "512-555-1001",
      email: "info@happytails.org",
      website: "https://happytails.org",
      description: "A no-kill shelter dedicated to finding forever homes for dogs and cats in Central Texas.",
      operatingHours: "Mon-Sat 10AM-6PM, Sun 12PM-5PM",
      capacity: 50,
      isActive: true,
      createdAt: now,
      updatedAt: now,
    });

    const shelter2 = await ctx.db.insert("shelters", {
      name: "PetSafe Haven",
      address: "456 Whisker Lane",
      city: "Austin",
      state: "TX",
      zipCode: "78702",
      phone: "512-555-1002",
      email: "info@petsafe.org",
      website: "https://petsafe.org",
      description: "Specializing in small animals and birds. Open adoption events every weekend.",
      operatingHours: "Tue-Sun 9AM-5PM",
      capacity: 30,
      isActive: true,
      createdAt: now,
      updatedAt: now,
    });

    const shelter3 = await ctx.db.insert("shelters", {
      name: "Second Chance Shelter",
      address: "789 Paw Avenue",
      city: "Round Rock",
      state: "TX",
      zipCode: "78664",
      phone: "512-555-1003",
      email: "hello@secondchance.org",
      description: "Giving animals a second chance at a loving home.",
      operatingHours: "Mon-Fri 8AM-4PM",
      capacity: 40,
      isActive: true,
      createdAt: now,
      updatedAt: now,
    });

    // ── Staff Assignments ──
    await ctx.db.insert("staffAssignments", {
      userId: staffUser1,
      shelterId: shelter1,
      role: "Manager",
      isActive: true,
      assignedAt: now,
      createdAt: now,
    });

    await ctx.db.insert("staffAssignments", {
      userId: staffUser2,
      shelterId: shelter2,
      role: "Caretaker",
      isActive: true,
      assignedAt: now,
      createdAt: now,
    });

    // ── Animals ──
    const buddy = await ctx.db.insert("animals", {
      name: "Buddy",
      species: "Dog",
      breed: "Golden Retriever",
      age: "Adult",
      gender: "Male",
      size: "Large",
      weight: 65,
      color: "Golden",
      description: "Friendly and energetic golden retriever who loves playing fetch and swimming. Great with kids and other dogs.",
      photoUrl: "https://images.unsplash.com/photo-1552053831-71594a27632d?w=600&h=400&fit=crop",
      medicalStatus: "Healthy",
      isSpayedNeutered: true,
      isVaccinated: true,
      isMicrochipped: true,
      temperament: "Friendly, playful, gentle",
      goodWithKids: true,
      goodWithDogs: true,
      goodWithCats: false,
      adoptionFee: 250,
      status: "Available",
      shelterId: shelter1,
      intakeDate: now - 86400000 * 30,
      createdAt: now,
      updatedAt: now,
    });

    const luna = await ctx.db.insert("animals", {
      name: "Luna",
      species: "Cat",
      breed: "Domestic Shorthair",
      age: "Young",
      gender: "Female",
      size: "Small",
      weight: 8,
      color: "Black and white",
      description: "Sweet and curious cat who loves window perches and lap time. Very gentle.",
      photoUrl: "https://images.unsplash.com/photo-1574158622682-e40e69881006?w=600&h=400&fit=crop",
      medicalStatus: "Healthy",
      isSpayedNeutered: true,
      isVaccinated: true,
      isMicrochipped: false,
      temperament: "Curious, affectionate, calm",
      goodWithKids: true,
      goodWithDogs: false,
      goodWithCats: true,
      adoptionFee: 150,
      status: "Available",
      shelterId: shelter1,
      intakeDate: now - 86400000 * 20,
      createdAt: now,
      updatedAt: now,
    });

    const max = await ctx.db.insert("animals", {
      name: "Max",
      species: "Dog",
      breed: "Labrador Mix",
      age: "Puppy/Kitten",
      gender: "Male",
      size: "Medium",
      weight: 25,
      color: "Chocolate",
      description: "Energetic puppy looking for an active family. Currently in training classes.",
      photoUrl: "https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=600&h=400&fit=crop",
      medicalStatus: "Healthy",
      isSpayedNeutered: false,
      isVaccinated: true,
      isMicrochipped: false,
      temperament: "Energetic, playful, eager to learn",
      goodWithKids: true,
      goodWithDogs: true,
      goodWithCats: false,
      adoptionFee: 300,
      status: "Available",
      shelterId: shelter2,
      intakeDate: now - 86400000 * 10,
      createdAt: now,
      updatedAt: now,
    });

    const whiskers = await ctx.db.insert("animals", {
      name: "Whiskers",
      species: "Rabbit",
      breed: "Holland Lop",
      age: "Adult",
      gender: "Female",
      size: "Small",
      weight: 4,
      color: "White and brown",
      description: "Gentle rabbit who enjoys being held and exploring. Litter trained.",
      photoUrl: "https://images.unsplash.com/photo-1585110396000-c9ffd4e4b308?w=600&h=400&fit=crop",
      medicalStatus: "Healthy",
      isSpayedNeutered: true,
      isVaccinated: true,
      isMicrochipped: false,
      temperament: "Gentle, curious",
      goodWithKids: true,
      goodWithDogs: false,
      goodWithCats: false,
      adoptionFee: 75,
      status: "Available",
      shelterId: shelter2,
      intakeDate: now - 86400000 * 15,
      createdAt: now,
      updatedAt: now,
    });

    const charlie = await ctx.db.insert("animals", {
      name: "Charlie",
      species: "Dog",
      breed: "Beagle",
      age: "Senior",
      gender: "Male",
      size: "Medium",
      weight: 30,
      color: "Tricolor",
      description: "Calm senior beagle looking for a quiet home. Loves belly rubs and naps.",
      photoUrl: "https://images.unsplash.com/photo-1505628346881-b72b27e84530?w=600&h=400&fit=crop",
      medicalStatus: "SpecialNeeds",
      isSpayedNeutered: true,
      isVaccinated: true,
      isMicrochipped: true,
      temperament: "Calm, gentle, loyal",
      goodWithKids: true,
      goodWithDogs: true,
      goodWithCats: true,
      specialNeeds: "Requires daily joint supplement medication",
      adoptionFee: 100,
      status: "Pending",
      shelterId: shelter3,
      intakeDate: now - 86400000 * 60,
      createdAt: now,
      updatedAt: now,
    });

    // Additional animals for variety
    await ctx.db.insert("animals", {
      name: "Daisy",
      species: "Dog",
      breed: "Golden Retriever",
      age: "Young",
      gender: "Female",
      size: "Large",
      weight: 55,
      color: "Golden",
      description: "Sweet and loyal golden retriever who loves outdoor adventures and cuddling on the couch.",
      photoUrl: "https://images.unsplash.com/photo-1561037404-61cd46aa615b?w=600&h=400&fit=crop",
      medicalStatus: "Healthy",
      isSpayedNeutered: true,
      isVaccinated: true,
      isMicrochipped: true,
      temperament: "Loyal, gentle, playful",
      goodWithKids: true,
      goodWithDogs: true,
      goodWithCats: true,
      adoptionFee: 275,
      status: "Available",
      shelterId: shelter1,
      intakeDate: now - 86400000 * 12,
      createdAt: now,
      updatedAt: now,
    });

    await ctx.db.insert("animals", {
      name: "Rocky",
      species: "Dog",
      breed: "German Shepherd Mix",
      age: "Adult",
      gender: "Male",
      size: "Large",
      weight: 70,
      color: "Black and Tan",
      description: "Intelligent and protective German Shepherd mix. Needs an experienced owner with a large yard.",
      photoUrl: "https://images.unsplash.com/photo-1518717758536-85ae29035b6d?w=600&h=400&fit=crop",
      medicalStatus: "Healthy",
      isSpayedNeutered: true,
      isVaccinated: true,
      isMicrochipped: true,
      temperament: "Intelligent, loyal, protective",
      goodWithKids: false,
      goodWithDogs: true,
      goodWithCats: false,
      adoptionFee: 200,
      status: "Available",
      shelterId: shelter3,
      intakeDate: now - 86400000 * 25,
      createdAt: now,
      updatedAt: now,
    });

    await ctx.db.insert("animals", {
      name: "Mochi",
      species: "Cat",
      breed: "Orange Tabby",
      age: "Adult",
      gender: "Male",
      size: "Medium",
      weight: 12,
      color: "Orange",
      description: "Chill orange tabby who loves to lounge in sunny spots. Great apartment cat.",
      photoUrl: "https://images.unsplash.com/photo-1495360010541-f48722b34f7d?w=600&h=400&fit=crop",
      medicalStatus: "Healthy",
      isSpayedNeutered: true,
      isVaccinated: true,
      isMicrochipped: false,
      temperament: "Relaxed, friendly, independent",
      goodWithKids: true,
      goodWithDogs: false,
      goodWithCats: true,
      adoptionFee: 125,
      status: "Available",
      shelterId: shelter2,
      intakeDate: now - 86400000 * 18,
      createdAt: now,
      updatedAt: now,
    });

    await ctx.db.insert("animals", {
      name: "Snowball",
      species: "Cat",
      breed: "Persian",
      age: "Senior",
      gender: "Female",
      size: "Medium",
      weight: 10,
      color: "White",
      description: "Elegant Persian cat seeking a quiet, loving home. Enjoys being brushed and pampered.",
      photoUrl: "https://images.unsplash.com/photo-1526336024174-e58f5cdd8e13?w=600&h=400&fit=crop",
      medicalStatus: "SpecialNeeds",
      isSpayedNeutered: true,
      isVaccinated: true,
      isMicrochipped: true,
      temperament: "Calm, affectionate, dignified",
      goodWithKids: false,
      goodWithDogs: false,
      goodWithCats: true,
      specialNeeds: "Requires daily eye cleaning and regular grooming",
      adoptionFee: 100,
      status: "Available",
      shelterId: shelter1,
      intakeDate: now - 86400000 * 45,
      createdAt: now,
      updatedAt: now,
    });

    await ctx.db.insert("animals", {
      name: "Peanut",
      species: "Other",
      breed: "Syrian Hamster",
      age: "Young",
      gender: "Male",
      size: "Small",
      weight: 0.3,
      color: "Golden brown",
      description: "Adorable hamster who loves running on his wheel and stuffing his cheeks. Great starter pet!",
      photoUrl: "https://images.unsplash.com/photo-1548767797-d8c844163c4c?w=600&h=400&fit=crop",
      medicalStatus: "Healthy",
      isSpayedNeutered: false,
      isVaccinated: false,
      isMicrochipped: false,
      temperament: "Curious, active, friendly",
      goodWithKids: true,
      goodWithDogs: false,
      goodWithCats: false,
      adoptionFee: 25,
      status: "Available",
      shelterId: shelter2,
      intakeDate: now - 86400000 * 7,
      createdAt: now,
      updatedAt: now,
    });

    await ctx.db.insert("animals", {
      name: "Cooper",
      species: "Dog",
      breed: "Labrador Retriever",
      age: "Puppy/Kitten",
      gender: "Male",
      size: "Medium",
      weight: 20,
      color: "Yellow",
      description: "Adorable lab puppy full of energy and love. Will grow into a loyal family companion.",
      photoUrl: "https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=600&h=400&fit=crop",
      medicalStatus: "Healthy",
      isSpayedNeutered: false,
      isVaccinated: true,
      isMicrochipped: false,
      temperament: "Energetic, friendly, eager to please",
      goodWithKids: true,
      goodWithDogs: true,
      goodWithCats: false,
      adoptionFee: 350,
      status: "Pending",
      shelterId: shelter1,
      intakeDate: now - 86400000 * 5,
      createdAt: now,
      updatedAt: now,
    });

    await ctx.db.insert("animals", {
      name: "Pierre",
      species: "Dog",
      breed: "French Bulldog",
      age: "Adult",
      gender: "Male",
      size: "Small",
      weight: 22,
      color: "Brindle",
      description: "Charming Frenchie with a big personality. Perfect for apartment living.",
      photoUrl: "https://images.unsplash.com/photo-1583337130417-13219a2323c1?w=600&h=400&fit=crop",
      medicalStatus: "Healthy",
      isSpayedNeutered: true,
      isVaccinated: true,
      isMicrochipped: true,
      temperament: "Playful, stubborn, affectionate",
      goodWithKids: true,
      goodWithDogs: true,
      goodWithCats: false,
      adoptionFee: 400,
      status: "Available",
      shelterId: shelter3,
      intakeDate: now - 86400000 * 14,
      createdAt: now,
      updatedAt: now,
    });

    await ctx.db.insert("animals", {
      name: "Cleo",
      species: "Cat",
      breed: "Domestic Shorthair",
      age: "Puppy/Kitten",
      gender: "Female",
      size: "Small",
      weight: 3,
      color: "Gray tabby",
      description: "Tiny kitten with huge eyes and a playful spirit. Will need patience for litter training.",
      photoUrl: "https://images.unsplash.com/photo-1596854407944-bf87f6fdd49e?w=600&h=400&fit=crop",
      medicalStatus: "Healthy",
      isSpayedNeutered: false,
      isVaccinated: true,
      isMicrochipped: false,
      temperament: "Playful, curious, energetic",
      goodWithKids: true,
      goodWithDogs: false,
      goodWithCats: true,
      adoptionFee: 175,
      status: "Available",
      shelterId: shelter2,
      intakeDate: now - 86400000 * 3,
      createdAt: now,
      updatedAt: now,
    });

    await ctx.db.insert("animals", {
      name: "Ghost",
      species: "Dog",
      breed: "Siberian Husky",
      age: "Young",
      gender: "Male",
      size: "Large",
      weight: 50,
      color: "White and gray",
      description: "Stunning husky with bright blue eyes. Needs lots of exercise and a securely fenced yard.",
      photoUrl: "https://images.unsplash.com/photo-1425082661507-6af0db74b5b3?w=600&h=400&fit=crop",
      medicalStatus: "Healthy",
      isSpayedNeutered: true,
      isVaccinated: true,
      isMicrochipped: true,
      temperament: "Energetic, vocal, independent",
      goodWithKids: true,
      goodWithDogs: true,
      goodWithCats: false,
      adoptionFee: 300,
      status: "Available",
      shelterId: shelter3,
      intakeDate: now - 86400000 * 22,
      createdAt: now,
      updatedAt: now,
    });

    await ctx.db.insert("animals", {
      name: "Mittens",
      species: "Cat",
      breed: "Maine Coon Mix",
      age: "Adult",
      gender: "Female",
      size: "Large",
      weight: 14,
      color: "Brown tabby",
      description: "Majestic Maine Coon mix with a fluffy tail and gentle disposition. Loves to follow you around.",
      photoUrl: "https://images.unsplash.com/photo-1573865526739-10659fec78a5?w=600&h=400&fit=crop",
      medicalStatus: "Healthy",
      isSpayedNeutered: true,
      isVaccinated: true,
      isMicrochipped: true,
      temperament: "Gentle, curious, sociable",
      goodWithKids: true,
      goodWithDogs: true,
      goodWithCats: true,
      adoptionFee: 200,
      status: "Adopted",
      shelterId: shelter1,
      intakeDate: now - 86400000 * 90,
      adoptedDate: now - 86400000 * 10,
      createdAt: now,
      updatedAt: now,
    });

    await ctx.db.insert("animals", {
      name: "Thumper",
      species: "Rabbit",
      breed: "Mini Rex",
      age: "Young",
      gender: "Male",
      size: "Small",
      weight: 3.5,
      color: "Gray",
      description: "Energetic mini rex who loves to binky and explore. Soft velvety fur.",
      photoUrl: "https://images.unsplash.com/photo-1585110396000-c9ffd4e4b308?w=600&h=400&fit=crop",
      medicalStatus: "Healthy",
      isSpayedNeutered: true,
      isVaccinated: false,
      isMicrochipped: false,
      temperament: "Energetic, friendly, playful",
      goodWithKids: true,
      goodWithDogs: false,
      goodWithCats: false,
      adoptionFee: 60,
      status: "Available",
      shelterId: shelter3,
      intakeDate: now - 86400000 * 8,
      createdAt: now,
      updatedAt: now,
    });

    await ctx.db.insert("animals", {
      name: "Kiwi",
      species: "Bird",
      breed: "Cockatiel",
      age: "Adult",
      gender: "Male",
      size: "Small",
      weight: 0.1,
      color: "Gray and yellow",
      description: "Friendly cockatiel who loves to whistle tunes and sit on shoulders. Hand-tamed.",
      photoUrl: "https://images.unsplash.com/photo-1548767797-d8c844163c4c?w=600&h=400&fit=crop",
      medicalStatus: "Healthy",
      isSpayedNeutered: false,
      isVaccinated: false,
      isMicrochipped: false,
      temperament: "Social, vocal, affectionate",
      goodWithKids: true,
      goodWithDogs: false,
      goodWithCats: false,
      adoptionFee: 50,
      status: "Available",
      shelterId: shelter2,
      intakeDate: now - 86400000 * 35,
      createdAt: now,
      updatedAt: now,
    });

    // ── Applications ──
    await ctx.db.insert("applications", {
      animalId: buddy,
      applicantId: adopter1,
      applicantName: "Emily Johnson",
      applicantEmail: "emily@example.com",
      applicantPhone: "512-555-0004",
      housingType: "House",
      hasYard: true,
      yardFenced: true,
      householdMembers: 2,
      hasChildren: false,
      experienceLevel: "Experienced",
      personalStatement: "I have had dogs my whole life and recently lost my beloved lab. I am ready to open my heart to Buddy.",
      status: "UnderReview",
      createdAt: now - 86400000 * 5,
      updatedAt: now - 86400000 * 3,
    });

    await ctx.db.insert("applications", {
      animalId: charlie,
      applicantId: adopter2,
      applicantName: "James Wilson",
      applicantEmail: "james@example.com",
      applicantPhone: "512-555-0005",
      housingType: "House",
      hasYard: true,
      yardFenced: true,
      otherPets: "One cat (indoor)",
      householdMembers: 4,
      hasChildren: true,
      childrenAges: "6 and 9",
      experienceLevel: "SomeExperience",
      personalStatement: "Our family is looking for a gentle dog that would be great with our kids. Charlie seems perfect.",
      status: "Submitted",
      createdAt: now - 86400000 * 2,
      updatedAt: now - 86400000 * 2,
    });

    await ctx.db.insert("applications", {
      animalId: luna,
      applicantId: adopter1,
      applicantName: "Emily Johnson",
      applicantEmail: "emily@example.com",
      applicantPhone: "512-555-0004",
      housingType: "House",
      hasYard: true,
      yardFenced: true,
      householdMembers: 2,
      hasChildren: false,
      experienceLevel: "Experienced",
      personalStatement: "Luna would be a perfect companion for quiet evenings at home.",
      status: "Submitted",
      createdAt: now - 86400000 * 1,
      updatedAt: now - 86400000 * 1,
    });

    // ── Notifications ──
    await ctx.db.insert("notifications", {
      userId: staffUser1,
      type: "ApplicationSubmitted",
      title: "New Application Received",
      message: "Emily Johnson submitted an application for Buddy",
      link: "/review-applications",
      isRead: false,
      createdAt: now - 86400000 * 5,
    });

    await ctx.db.insert("notifications", {
      userId: adopter1,
      type: "ApplicationStatusChanged",
      title: "Application Under Review",
      message: "Your application for Buddy is now under review",
      link: "/my-applications",
      isRead: true,
      createdAt: now - 86400000 * 3,
    });

    await ctx.db.insert("notifications", {
      userId: adopter1,
      type: "AnimalStatusChanged",
      title: "New Animal Listed",
      message: "A new Golden Retriever named Buddy has been listed at Happy Tails Rescue",
      link: "/animals",
      isRead: false,
      createdAt: now - 86400000 * 30,
    });

    // ── User Settings ──
    await ctx.db.insert("userSettings", {
      userId: adopter1,
      emailNotifications: true,
      applicationUpdates: true,
      newAnimalAlerts: true,
      preferredSpecies: ["Dog", "Cat"],
      preferredSize: ["Medium", "Large"],
      updatedAt: now,
    });

    await ctx.db.insert("userSettings", {
      userId: adopter2,
      emailNotifications: true,
      applicationUpdates: true,
      newAnimalAlerts: false,
      preferredSpecies: ["Dog"],
      preferredSize: ["Medium"],
      updatedAt: now,
    });

    console.log("Seed data inserted successfully!");
  },
});